### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ahmedwafdi** [fridolin-koch/VreshTwilioBundle#13]
o have this Error 
SSL certificate problem: self signed certificate in certificate chain

**Comment by fridolin-koch** [comment]
Seems more like a problem with your environment. See here: http://stackoverflow.com/a/28545924/1176615

**Comment by fridolin-koch** [comment]
See also: https://github.com/twilio/twilio-php/issues/203
