### ISSUE TITLE
Twilio Lookups Service

### ISSUE THREAD

**Issue by ahmedwafdi** [fridolin-koch/VreshTwilioBundle#14]
I just wanna know if this bundle provide the service of Lookups ?

**Comment by fridolin-koch** [comment]
Hi,

while check it out, I decided to implement it :-) 

Twilio Lookups Service are supported in Version [0.5.0](https://github.com/fridolin-koch/VreshTwilioBundle/releases/tag/v0.5.0)

You can use it like that

```php
// assuming you are inside a controller
$lookups = $this->get('twilio.lookups');
$number = $lookups->phone_numbers->get("+15108675309");
```
